global using System;
global using System.Collections.Generic;
global using System.Linq;
global using NUnit.Framework;
global using OpenQA.Selenium;
global using OpenQA.Selenium.Chrome;
global using OpenQA.Selenium.Interactions;
global using OpenQA.Selenium.Support.UI;
global using WebDriverManager.DriverConfigs.Impl;