version: 2.1
jobs:
  build:
    machine:
      image: windows-server-2019-vs2019:stable
    environment:
      dotnet: C:\Program Files\dotnet\dotnet.exe
    steps:
      - checkout
      - run:
          command: |
            $env:PATH += ';C:\Program Files\dotnet'
            dotnet build
      - run:
          command: |
            $env:PATH += ';C:\Program Files\dotnet'
            dotnet test
      - store_test_results:
          path: Patterns/TestResults
      - store_artifacts:
          path: Patterns/bin/Debug/net6.0
          destination: build-artifacts
      - run:
          command: |
            $env:PATH += ';C:\Program Files\dotnet'
            allure generate Patterns/bin/Debug/net6.0/allure-results -o build-artifacts/allure-report
workflows:
  version: 2
  build:
    jobs:
      - build
