version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
	  name: sr-dev-ldap
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build --configuration Release
      - run:
          name: Run tests
          command: dotnet test --configuration Release --logger:trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - run:
          name: Generate Allure report
          command: |
            dotnet add package Allure.NUnit
            dotnet add package Allure.Commons
            dotnet add package Microsoft.Extensions.FileSystemGlobbing
            dotnet add package Microsoft.Extensions.FileSystemGlobbing.Abstractions
            dotnet test --no-build --configuration Release /p:AllureResultsDirectory=TestResults/allure-results /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
            dotnet tool install -g ReportGenerator
            reportgenerator -reports:TestResults/**/coverage.opencover.xml -targetdir:TestResults/CoverageReport
            allure generate TestResults/allure-results -o TestResults/allure-report --clean
          when: always

workflows:
  build-and-test:
    jobs:
      - build