version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        environment:
          TZ: "America/New_York"
      - image: selenium/standalone-chrome:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: dotnet restore
      - run:
          name: Build solution
          command: dotnet build
      - run:
          name: Run tests and generate Allure report
          command: |
            dotnet test --filter "TestCategory=Smoke" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
            dotnet tool install -g allure-commandline
            allure generate TestResults -o TestResults/AllureReport --clean
      - store_artifacts:
          path: TestResults
          destination: test-results
      - store_artifacts:
          path: TestResults/AllureReport
          destination: allure-report

workflows:
  build:
    jobs:
      - build