version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        environment:
          NUGET_XMLDOC_MODE: skip
          ASPNETCORE_ENVIRONMENT: "Development"
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build project
          command: dotnet build --configuration Release
      - run:
          name: Run tests
          command: |
            dotnet test --configuration Release --logger "trx;LogFileName=test_results.xml" --collect:"XPlat Code Coverage"
      - run:
          name: Generate Allure report
          command: |
            dotnet tool install Allure.Commandline --tool-path ./allure
            ./allure/allure-2.15.0/bin/allure generate ./TestResults/ -o ./AllureReport/ --clean
          when: always
      - store_artifacts:
          path: AllureReport/
          destination: allure-report

workflows:
  version: 2
  build:
    jobs:
      - build