version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        environment:
          NUGET_XMLDOC_MODE: skip
          ASPNETCORE_ENVIRONMENT: "Development"
    steps:
      - checkout
      - run:
<<<<<<< Updated upstream
          name: Restore dependencies
=======
          name: Install Chrome and Chromedriver
          command: |
            apt-get update
            apt-get install -y wget unzip gnupg2
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | tee -a /etc/apt/sources.list.d/google-chrome.list
            apt-get update
            apt-get install -y google-chrome-stable
            LATEST=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
            wget https://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            chmod +x chromedriver
            mv chromedriver /usr/local/bin/
      - run:
          name: Install Dependencies
>>>>>>> Stashed changes
          command: dotnet restore
      - run:
          name: Build project
          command: dotnet build --configuration Release
      - run:
          name: Run tests
          command: |
            dotnet test --configuration Release --logger "trx;LogFileName=test_results.xml" --collect:"XPlat Code Coverage"
      - run:
          name: Generate Allure report
          command: |
            dotnet tool install Allure.Commandline --tool-path ./allure
            ./allure/allure-2.15.0/bin/allure generate ./TestResults/ -o ./AllureReport/ --clean
          when: always
      - store_artifacts:
          path: AllureReport/
          destination: allure-report

workflows:
  version: 2
  build:
    jobs:
      - build