version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
        environment:
          TZ: "America/New_York"
      - image: selenium/standalone-chrome:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: dotnet restore
      - run:
          name: Build solution
          command: dotnet build
      - run:
          name: Run tests
          command: dotnet test --filter "TestCategory=Smoke" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - store_artifacts:
          path: TestResults
          destination: test-results
      - store_artifacts:
          path: coverage.opencover.xml
          destination: test-results

workflows:
  build:
    jobs:
      - build