version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet tool install --global allure-commandline --version 2.16.0
      - run: dotnet test --logger:trx --results-directory:./TestResults
      - run: allure generate ./TestResults -c -o ./TestReport && allure open ./TestReport