version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
      - image: selenium/standalone-chrome
    steps:
      - checkout
      - run: dotnet restore
      - run:
          name: Run tests
          command: |
            dotnet test --logger:trx --results-directory TestResults
      - run:
          name: Generate Allure report
          command: |
            allure generate TestResults -o allure-report --clean
          when: always

workflows:
  build_and_test:
    jobs:
      - build