version: 2.1

orbs:
  win: circleci/windows@5.0.0

commands:
  report:
    steps:
    - store_test_results:
        path: Test/TestResults
    - store_artifacts:
        path: Test/TestResults

jobs:
  test-windows:
    executor:
      name: win/default
    steps:
      - checkout
      - run: ./scripts/install-windows.ps1
      - run: dotnet build -c Release
      - run: bash scripts/test.sh --filter "TestCategory=WinDivert"
      - report