version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Install Chrome and Chromedriver
          command: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
            apt-get update
            apt-get install google-chrome-stable
            LATEST=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
            wget https://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            chmod +x chromedriver
            mv chromedriver /usr/local/bin/
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "*.csproj" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: dotnet restore
      - save_cache:
          key: v1-dependencies-{{ checksum "*.csproj" }}
          paths:
            - ~/.nuget/packages
            - ./obj/project.assets.json
      - run:
          name: Build Solution
          command: dotnet build
      - run:
          name: Run Tests
          command: |
            export ASPNETCORE_ENVIRONMENT=Development
            export ASPNETCORE_URLS=http://localhost:5000
            dotnet test
          
      - run:
          name: Generate Allure report
          command: |
            dotnet tool install --global Allure.CommandLine
            allure --version
            mkdir allure-results
            dotnet test MyTestProject.csproj --logger:"nunit;LogFilePath=testresult.xml" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./lcov
            allure nunit2junit --input=./testresult.xml --output=./allure-results
            allure generate ./allure-results -o ./allure-report
    working_directory: ~/project
